steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy app.yaml --quiet

# Instead of top-level logging, do this:
options:
  logging: CLOUD_LOGGING_ONLY
