steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Example: Deploy to App Engine
        gcloud app deploy app.yaml --quiet

serviceAccount: projects/PROJECT_ID/serviceAccounts/YOUR_SERVICE_ACCOUNT

# This is how you specify a custom bucket for logs:
logsBucket: gs://collab-dict-bucket

options:
  # logging is an enum if you want to set e.g. 'CLOUD_LOGGING_ONLY'
  logging: GCS_ONLY
